### ISSUE TITLE
the import dlls libs/PatchEngine is not found.

### ISSUE THREAD

**Issue by fuchanghao** [Secant1006/PSFExtractor#3]
The code

#ifdef _M_AMD64
IDR_DLL1 RCDATA "libs/PatchEngine/x64/mspatcha.dll"
IDR_DLL2 RCDATA "libs/PatchEngine/x64/msdelta.dll"
#elif defined _M_IX86
IDR_DLL1 RCDATA "libs/PatchEngine/x86/mspatcha.dll"
IDR_DLL2 RCDATA "libs/PatchEngine/x86/msdelta.dll"
#endif

Where can I found these dll files.

**Comment by Secant1006** [comment]
They need to be extracted from Windows Vista installation image.

**Comment by fuchanghao** [comment]
> PatchEngine

Why the files from Windows Vista installation image should be chosen?

I tested with Visual Studio 2022+Windows 11 22H2 SDK+mspatcha.dll/msdelta.dll files from leatest Windows 11 22H2 stable SSU :[SSU-22621.378-x64.cab](https://uupdump.net/getfile.php?id=7c7aac60-93b5-4733-b7ee-d6fd13c9bce6&file=SSU-22621.378-x64.cab)

It seems works fine.

**Comment by Secant1006** [comment]
ApplyPatchToFileByBuffers() is only available in Windows Vista's mspatcha.dll and it's the latest one that is compatible with Windows 2000. Newer DLLs can work, only if your Windows version is new enough for them.

**Comment by fuchanghao** [comment]
> ApplyPatchToFileByBuffers

Will Windows Server 2008‘s file compatible with Windows 2000?

Like this one, SSU of  Windows Server 2008?

https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/07/windows6.0-kb5016129-x64_89f963d1f75a4afcc55c287d530c9336fbfbf2aa.msu

PS：for  compatible with Windows 2000, Which editions of Windows SDK And Visual C++ should be used.

PSS：About ApplyPatchToFileByBuffers()，This is available in “C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\PatchApi.h”.

**Comment by Secant1006** [comment]
I meant "Windows Vista and above", sorry for the wording.

I used Windows SDK v6.0 and Visual C++ 2005. Visual C++ 2005 is recommended for relatively painless Unicode API support and Windows 2000 compatibility. As for Windows SDK, since the program loads patch engine libraries dynamically the only non-system library that statically linked is Cabinet API. The API hasn't been changed since Windows 2000 so theoretically Windows 2000 SDK should be fine.

Windows Server 2008 shares the same kernel and API version as Windows Vista, therefore it should be compatible.

If you are interested you can test them out yourself. I'll just stick with the current versions I used as there's no issue with targeting platforms.
